### PR TITLE
Basic structure

### PR DESCRIPTION
**Pull request by knezi**
See issue #3

### CODE REVIEW

**Comment by ath88** [comment]
Looks good! For RPs that changes or creates something that has a visual facet, adding screenshots to the PR is very much encouraged. :) Could you attach one?

I like your idea of having meta-information about each page too. YAML is pretty nice for that sort of stuff.

**Comment by knezi** [comment]
Screenshot? For this nothing? But here you are :)
2017-03-30-143636_1366x768_scrot

Let's discuss YAML in the issue.

**Comment by ath88** [comment]
Adding screenshots makes it soo much easier to review visual stuff. Otherwise I have to check out the branch locally, which makes reviewing more cumbersome. :)

Structure looks good.

**Comment by knezi** [comment]
Oh, that's right. I forgot that you haven't got my branch :D.

**Comment by ath88** [comment]
The branch is on GitHub, but I have to manually check it out locally and open the HTML-files to view the rendered HTML. :)

**Comment by knezi** [comment]
Yes, sure. Next time I'll post it.

**Pull request merged**
